### PR TITLE
chart(brigade) move service and ingress blocks under gateway

### PR DESCRIPTION
**Pull request by rmb938**
Since the service and ingress blocks manage the gateway component it makes sense to stick them under the gateway block

### CODE REVIEW

**Review by vdice — APPROVED** [review]
Good call.  LGTM and thanks @rmb938 !

**Review by vdice — CHANGES_REQUESTED** [review]
Oops, looks like a linter/`make test` failure:
```
[ERROR] templates/: render error in "brigade/templates/gateway-github-deployment.yaml": template: brigade/templates/gateway-github-deployment.yaml:31:35: executing "brigade/templates/gateway-github-deployment.yaml" at <.Values.service.inte...>: can't evaluate field internalPort in type interface {}
```
Actually, it appears there are a few places where `Values.service.<value>` needs to be updated to `Values.gw.service.<value>`.

**Comment by rmb938** [comment]
ah I thought I got all of them, will fix.

**Comment by rmb938** [comment]
@vdice Fixed. I also remove the port block from the controller since it doesn't listen on any port.

**Review by vdice — APPROVED** [review]

**Comment by vdice** [comment]
@rmb938 nice catch on the controller amendment. 👍

**Pull request merged**
