### PR TITLE
generic-webhook related changes

### PR DESCRIPTION
**Pull request by dgkanatsios**
This PR includes the necessary Helm template changes regarding to the Generic Webhook Brigade implementation here: https://github.com/Azure/brigade/pull/721 

Needless to say, these two should be merged together.

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
Shall we update the brigade-project Helm chart (secret template) to add the following?
```
  {{if .Values.genericWebhookSecret -}}
  genericWebhookSecret: {{ .Values.genericWebhookSecret | quote }}
  {{- end }} 
```
This would be needed for Helm-managed projects to use this feature...

**Comment by dgkanatsios** [comment]
added, thank you!

**Review by vdice — APPROVED** [review]
LGTM pending merge of https://github.com/Azure/brigade/pull/721

**Comment by dgkanatsios** [comment]
Closing as Generic Gateway will be set-up as a separate gateway, to avoid exposing the API Server ([info](https://github.com/Azure/brigade/pull/762#issuecomment-454799925))

**Pull request closed without merging**
